package com.example.kotlinapi;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;

@Configuration
public class SpringDocConfiguration {

	@Bean
	public OpenAPI apiInfo() {
		return new OpenAPI()
				.info(new Info()
						.title("Sample API")
						.description("No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)")
						.version("1.0.0"));
	}
}
